import {
  Building2,
  Ticket,
  Fish,
  Palette,
  Banknote,
  Cake,
  Beer,
  Bike,
  BookOpen,
  Bus,
  Coffee,
  Tent,
  Car,
  CarFront,
  Droplets,
  Cross,
  Church,
  Scale,
  ShoppingBag,
  Pill,
  Zap,
  Cpu,
  Flame,
  Flower2,
  HeartPulse,
  Sofa,
  Fuel,
  Dumbbell,
  Scissors,
  Hammer,
  Building,
  Hospital,
  Shield,
  Gem,
  Shirt,
  Gavel,
  Library,
  Wine,
  Lock,
  Hotel,
  Utensils,
  PizzaIcon,
  Film,
  Clapperboard,
  Truck,
  Martini,
  Paintbrush,
  Trees,
  Dog,
  Syringe,
  Activity,
  Wrench,
  Mailbox,
  Home,
  UtensilsCrossed,
  HardHat,
  Caravan,
  School,
  Package,
  Store,
  ShoppingCart,
  Landmark,
  Train,
  Plane,
  GraduationCap,
  Stethoscope,
  Squirrel,
} from "lucide-react";
import { FaStore, FaUniversity } from "react-icons/fa";
import { RiGovernmentLine } from "react-icons/ri";
import { PiMosqueThin, PiPoliceCar, PiTooth } from "react-icons/pi";
import { LuPalmtree, LuParkingCircle } from "react-icons/lu";
import { TbShoe } from "react-icons/tb";
import { FaSpa } from "react-icons/fa6";
import {
  MdOutlineStadium,
  MdOutlineSynagogue,
  MdOutlineLocalTaxi,
} from "react-icons/md";
import { IoBowlingBallOutline, IoDiceOutline } from "react-icons/io5";

export const placeIcons = [
  { place: "accounting", icon: Building2 },
  { place: "airport", icon: Plane },
  { place: "amusement_park", icon: Ticket },
  { place: "aquarium", icon: Fish },
  { place: "art_gallery", icon: Palette },
  { place: "atm", icon: Banknote },
  { place: "bakery", icon: Cake },
  { place: "bank", icon: Building },
  { place: "bar", icon: Beer },
  { place: "beauty_salon", icon: Scissors },
  { place: "bicycle_store", icon: Bike },
  { place: "book_store", icon: BookOpen },
  { place: "bowling_alley", icon: IoBowlingBallOutline },
  { place: "bus_station", icon: Bus },
  { place: "cafe", icon: Coffee },
  { place: "campground", icon: Tent },
  { place: "car_dealer", icon: Car },
  { place: "car_rental", icon: CarFront },
  { place: "car_repair", icon: Wrench },
  { place: "car_wash", icon: Droplets },
  { place: "casino", icon: IoDiceOutline },
  { place: "cemetery", icon: Cross },
  { place: "church", icon: Church },
  { place: "city_hall", icon: Building },
  { place: "clothing_store", icon: Shirt },
  { place: "convenience_store", icon: Store },
  { place: "courthouse", icon: Scale },
  { place: "dentist", icon: PiTooth },
  { place: "department_store", icon: ShoppingBag },
  { place: "doctor", icon: Stethoscope },
  { place: "drugstore", icon: Pill },
  { place: "electrician", icon: Zap },
  { place: "electronics_store", icon: Cpu },
  { place: "embassy", icon: Landmark },
  { place: "fire_station", icon: Flame },
  { place: "florist", icon: Flower2 },
  { place: "funeral_home", icon: HeartPulse },
  { place: "furniture_store", icon: Sofa },
  { place: "gas_station", icon: Fuel },
  { place: "gym", icon: Dumbbell },
  { place: "hair_care", icon: Scissors },
  { place: "hardware_store", icon: Hammer },
  { place: "hindu_temple", icon: Building },
  { place: "home_goods_store", icon: Home },
  { place: "hospital", icon: Hospital },
  { place: "insurance_agency", icon: Shield },
  { place: "jewelry_store", icon: Gem },
  { place: "laundry", icon: Shirt },
  { place: "lawyer", icon: Gavel },
  { place: "library", icon: Library },
  { place: "light_rail_station", icon: Train },
  { place: "liquor_store", icon: Wine },
  { place: "local_government_office", icon: RiGovernmentLine },
  { place: "locksmith", icon: Lock },
  { place: "lodging", icon: Hotel },
  { place: "meal_delivery", icon: Utensils },
  { place: "meal_takeaway", icon: PizzaIcon },
  { place: "mosque", icon: PiMosqueThin },
  { place: "movie_rental", icon: Film },
  { place: "movie_theater", icon: Clapperboard },
  { place: "moving_company", icon: Truck },
  { place: "museum", icon: LuPalmtree },
  { place: "night_club", icon: Martini },
  { place: "painter", icon: Paintbrush },
  { place: "park", icon: Trees },
  { place: "parking", icon: LuParkingCircle },
  { place: "pet_store", icon: Dog },
  { place: "pharmacy", icon: Syringe },
  { place: "physiotherapist", icon: Activity },
  { place: "plumber", icon: Wrench },
  { place: "police", icon: PiPoliceCar },
  { place: "post_office", icon: Mailbox },
  { place: "primary_school", icon: GraduationCap },
  { place: "real_estate_agency", icon: Home },
  { place: "restaurant", icon: UtensilsCrossed },
  { place: "roofing_contractor", icon: HardHat },
  { place: "rv_park", icon: Caravan },
  { place: "school", icon: School },
  { place: "secondary_school", icon: School },
  { place: "shoe_store", icon: TbShoe },
  { place: "shopping_mall", icon: ShoppingCart },
  { place: "spa", icon: FaSpa },
  { place: "stadium", icon: MdOutlineStadium },
  { place: "storage", icon: Package },
  { place: "store", icon: FaStore },
  { place: "subway_station", icon: Train },
  { place: "supermarket", icon: ShoppingCart },
  { place: "synagogue", icon: MdOutlineSynagogue },
  { place: "taxi_stand", icon: MdOutlineLocalTaxi },
  { place: "tourist_attraction", icon: Landmark },
  { place: "train_station", icon: Train },
  { place: "transit_station", icon: Train },
  { place: "travel_agency", icon: Plane },
  { place: "university", icon: FaUniversity },
  { place: "veterinary_care", icon: Stethoscope },
  { place: "zoo", icon: Squirrel },
];
